# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "cpp-scaffold/maintainers"
    assignees:
      - "cpp-scaffold/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Python dependencies (for CI scripts)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "cpp-scaffold/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "cpp-scaffold/maintainers"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # Git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00"
    open-pull-requests-limit: 2
    reviewers:
      - "cpp-scaffold/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "submodules"
      - "automated"
