// Test file for test-xmake-modules module
// Generated by CPP-Scaffold

import test-xmake-modules;
import std;
#include <gtest/gtest.h>

class test-xmake-modulesTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Setup code here
    }

    void TearDown() override {
        // Cleanup code here
    }
};

TEST_F(test-xmake-modulesTest, ExampleConstructor) {
    test-xmake-modules::Example example(42);
    EXPECT_EQ(example.getValue(), 42);
}

TEST_F(test-xmake-modulesTest, ExampleSetValue) {
    test-xmake-modules::Example example(0);
    example.setValue(100);
    EXPECT_EQ(example.getValue(), 100);
}

TEST_F(test-xmake-modulesTest, AddFunction) {
    int result = test-xmake-modules::add(3, 4);
    EXPECT_EQ(result, 7);
}

TEST_F(test-xmake-modulesTest, GetVersion) {
    std::string version = test-xmake-modules::getVersion();
    EXPECT_FALSE(version.empty());
    EXPECT_EQ(version, "1.0.0");
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
