// test-xmake-modules - C++20 Module Interface
// Generated by CPP-Scaffold

export module test-xmake-modules;

import std;

export namespace test-xmake-modules {
    // Example class
    class Example {
    public:
        explicit Example(int value);
        int getValue() const;
        void setValue(int value);

    private:
        int value_;
    };

    // Example function
    int add(int a, int b);

    // Version information
    std::string getVersion();
}
