# Codecov configuration for C++ project
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches:
          - main
          - develop
    patch:
      default:
        target: 75%
        threshold: 2%
        base: auto

  ignore:
    - "tests/"
    - "examples/"
    - "docs/"
    - "build/"
    - "cmake/"
    - "scripts/"
    - "src/main.cpp"
    - "**/*.test.cpp"
    - "**/*_test.cpp"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 80%
      - type: patch
        target: 75%

flags:
  unittests:
    paths:
      - src/
    carryforward: true
