// test-xmake-modules - Main Application
// Generated by CPP-Scaffold

import test-xmake-modules;
import std;

int main() {
    std::println("Welcome to {}!", "test-xmake-modules");

    // Create an Example object
    test-xmake-modules::Example example(42);

    // Use the example object
    int value = example.getValue();
    std::println("Example value: {}", value);

    // Use a free function
    int sum = test-xmake-modules::add(3, 4);
    std::println("3 + 4 = {}", sum);

    // Get version
    std::string version = test-xmake-modules::getVersion();
    std::println("Version: {}", version);

    return 0;
}
