// test-xmake-modules - C++20 Module Implementation
// Generated by CPP-Scaffold

module test-xmake-modules;

namespace test-xmake-modules {
    Example::Example(int value) : value_(value) {}

    int Example::getValue() const {
        return value_;
    }

    void Example::setValue(int value) {
        value_ = value;
    }

    int add(int a, int b) {
        return a + b;
    }

    std::string getVersion() {
        return "1.0.0";
    }
}
