#ifndef TEST-PREMAKE-LIB_VERSION_H
#define TEST-PREMAKE-LIB_VERSION_H

#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_PATCH 0

#define VERSION_STR "0.1.0"

#endif // TEST-PREMAKE-LIB_VERSION_H
