.TH CPP-SCAFFOLD 1 "2024" "cpp-scaffold 1.0.0" "User Commands"
.SH NAME
cpp-scaffold \- C++ project scaffolding tool
.SH SYNOPSIS
.B cpp-scaffold
[\fIOPTIONS\fR] [\fIPROJECT_NAME\fR]
.SH DESCRIPTION
.B cpp-scaffold
is a powerful, modern C++ project scaffolding tool that helps developers quickly create well-structured C++ projects with industry best practices, modern build systems, package managers, testing frameworks, and development tools.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit
.TP
.BR \-v ", " \-\-version
Show version information and exit
.TP
.BR \-t ", " \-\-type " " \fITYPE\fR
Project type (console, library, gui, network, embedded, webservice)
.TP
.BR \-b ", " \-\-build " " \fISYSTEM\fR
Build system (cmake, meson, bazel, xmake, premake, make, ninja)
.TP
.BR \-p ", " \-\-package " " \fIMANAGER\fR
Package manager (vcpkg, conan, spack, hunter)
.TP
.BR \-\-test " " \fIFRAMEWORK\fR
Testing framework (gtest, catch2, doctest, boost-test)
.TP
.BR \-\-ci " " \fISYSTEM\fR
CI/CD system (github, gitlab, travis, appveyor, azure, circleci)
.TP
.BR \-\-editor " " \fIEDITOR\fR
IDE/Editor (vscode, clion, visual-studio, vim, emacs)
.TP
.BR \-\-framework " " \fIFRAMEWORK\fR
GUI framework (qt, gtk, fltk, wxwidgets) for GUI projects
.TP
.BR \-\-interactive
Run in interactive mode (default)
.TP
.BR \-\-no-interactive
Run in non-interactive mode
.SH EXAMPLES
.TP
Create a project interactively:
.B cpp-scaffold
.TP
Create a console application with CMake and vcpkg:
.B cpp-scaffold MyProject --type console --build cmake --package vcpkg
.TP
Create a GUI application with Qt:
.B cpp-scaffold MyApp --type gui --framework qt --build cmake --package vcpkg --test gtest
.TP
Create a library with comprehensive setup:
.B cpp-scaffold MyLib --type library --build cmake --package conan --test catch2 --ci github --editor vscode
.SH FILES
.TP
.I ~/.config/cpp-scaffold/config.json
User configuration file
.TP
.I ~/.cache/cpp-scaffold/
Template cache directory
.SH ENVIRONMENT
.TP
.B CPP_SCAFFOLD_CONFIG
Path to configuration file
.TP
.B CPP_SCAFFOLD_CACHE_DIR
Path to cache directory
.SH SEE ALSO
.BR cmake (1),
.BR ninja (1),
.BR git (1)
.SH BUGS
Report bugs at: https://github.com/cpp-scaffold/cpp-scaffold/issues
.SH AUTHOR
CPP-Scaffold Team <support@cpp-scaffold.org>
.SH COPYRIGHT
Copyright © 2024 CPP-Scaffold Team. Licensed under GPL-3.0.
